#region Copyright & license notice
/*
 * Copyright: Copyright (c) 2007 Amazon Technologies, Inc.
 * License:   Apache License, Version 2.0
 */
#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace Amazon.WebServices.MechanicalTurk.Domain{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/Quest" +
        "ionForm.xsd", IsNullable=false)]
    public partial class QuestionForm {
        
        private ContentType overviewField;
        
        private QuestionFormQuestion[] questionField;
        
        /// <remarks/>
        public ContentType Overview {
            get {
                return this.overviewField;
            }
            set {
                this.overviewField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Question")]
        public QuestionFormQuestion[] Question {
            get {
                return this.questionField;
            }
            set {
                this.questionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/Quest" +
        "ionForm.xsd")]
    public partial class ContentType {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Application", typeof(ApplicationContentType))]
        [System.Xml.Serialization.XmlElementAttribute("Binary", typeof(BinaryContentType))]
        [System.Xml.Serialization.XmlElementAttribute("FormattedContent", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("List", typeof(string[]))]
        [System.Xml.Serialization.XmlElementAttribute("Text", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Title", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/Quest" +
        "ionForm.xsd")]
    public partial class ApplicationContentType {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Flash", typeof(FlashContentType))]
        [System.Xml.Serialization.XmlElementAttribute("JavaApplet", typeof(JavaAppletContentType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/Quest" +
        "ionForm.xsd")]
    public partial class FlashContentType {
        
        private string flashMovieURLField;
        
        private string widthField;
        
        private string heightField;
        
        private ApplicationParameter[] applicationParameterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string FlashMovieURL {
            get {
                return this.flashMovieURLField;
            }
            set {
                this.flashMovieURLField = value;
            }
        }
        
        /// <remarks/>
        public string Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public string Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ApplicationParameter")]
        public ApplicationParameter[] ApplicationParameter {
            get {
                return this.applicationParameterField;
            }
            set {
                this.applicationParameterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/Quest" +
        "ionForm.xsd")]
    public partial class ApplicationParameter {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/Quest" +
        "ionForm.xsd")]
    public partial class FileUploadAnswerType {
        
        private string maxFileSizeInBytesField;
        
        private string minFileSizeInBytesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string MaxFileSizeInBytes {
            get {
                return this.maxFileSizeInBytesField;
            }
            set {
                this.maxFileSizeInBytesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string MinFileSizeInBytes {
            get {
                return this.minFileSizeInBytesField;
            }
            set {
                this.minFileSizeInBytesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/Quest" +
        "ionForm.xsd")]
    public partial class SelectionAnswerType {
        
        private string minSelectionCountField;
        
        private string maxSelectionCountField;
        
        private SelectionAnswerTypeStyleSuggestion styleSuggestionField;
        
        private bool styleSuggestionFieldSpecified;
        
        private SelectionAnswerTypeSelections selectionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string MinSelectionCount {
            get {
                return this.minSelectionCountField;
            }
            set {
                this.minSelectionCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string MaxSelectionCount {
            get {
                return this.maxSelectionCountField;
            }
            set {
                this.maxSelectionCountField = value;
            }
        }
        
        /// <remarks/>
        public SelectionAnswerTypeStyleSuggestion StyleSuggestion {
            get {
                return this.styleSuggestionField;
            }
            set {
                this.styleSuggestionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StyleSuggestionSpecified {
            get {
                return this.styleSuggestionFieldSpecified;
            }
            set {
                this.styleSuggestionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public SelectionAnswerTypeSelections Selections {
            get {
                return this.selectionsField;
            }
            set {
                this.selectionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum SelectionAnswerTypeStyleSuggestion {
        
        /// <remarks/>
        radiobutton,
        
        /// <remarks/>
        checkbox,
        
        /// <remarks/>
        list,
        
        /// <remarks/>
        dropdown,
        
        /// <remarks/>
        combobox,
        
        /// <remarks/>
        multichooser,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SelectionAnswerTypeSelections {
        
        private SelectionAnswerTypeSelectionsSelection[] selectionField;
        
        private FreeTextAnswerType otherSelectionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Selection")]
        public SelectionAnswerTypeSelectionsSelection[] Selection {
            get {
                return this.selectionField;
            }
            set {
                this.selectionField = value;
            }
        }
        
        /// <remarks/>
        public FreeTextAnswerType OtherSelection {
            get {
                return this.otherSelectionField;
            }
            set {
                this.otherSelectionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SelectionAnswerTypeSelectionsSelection {
        
        private string selectionIdentifierField;
        
        private object itemField;
        
        /// <remarks/>
        public string SelectionIdentifier {
            get {
                return this.selectionIdentifierField;
            }
            set {
                this.selectionIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Binary", typeof(BinaryContentType))]
        [System.Xml.Serialization.XmlElementAttribute("Text", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/Quest" +
        "ionForm.xsd")]
    public partial class BinaryContentType {
        
        private MimeType mimeTypeField;
        
        private string dataURLField;
        
        private string altTextField;
        
        /// <remarks/>
        public MimeType MimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string DataURL {
            get {
                return this.dataURLField;
            }
            set {
                this.dataURLField = value;
            }
        }
        
        /// <remarks/>
        public string AltText {
            get {
                return this.altTextField;
            }
            set {
                this.altTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/Quest" +
        "ionForm.xsd")]
    public partial class MimeType {
        
        private MimeTypeType typeField;
        
        private string subTypeField;
        
        /// <remarks/>
        public MimeTypeType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string SubType {
            get {
                return this.subTypeField;
            }
            set {
                this.subTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum MimeTypeType {
        
        /// <remarks/>
        image,
        
        /// <remarks/>
        audio,
        
        /// <remarks/>
        video,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/Quest" +
        "ionForm.xsd")]
    public partial class FreeTextAnswerType {
        
        private FreeTextAnswerTypeConstraints constraintsField;
        
        private string defaultTextField;
        
        private string numberOfLinesSuggestionField;
        
        /// <remarks/>
        public FreeTextAnswerTypeConstraints Constraints {
            get {
                return this.constraintsField;
            }
            set {
                this.constraintsField = value;
            }
        }
        
        /// <remarks/>
        public string DefaultText {
            get {
                return this.defaultTextField;
            }
            set {
                this.defaultTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string NumberOfLinesSuggestion {
            get {
                return this.numberOfLinesSuggestionField;
            }
            set {
                this.numberOfLinesSuggestionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FreeTextAnswerTypeConstraints {
        
        private FreeTextAnswerTypeConstraintsIsNumeric isNumericField;
        
        private FreeTextAnswerTypeConstraintsLength lengthField;
        
        /// <remarks/>
        public FreeTextAnswerTypeConstraintsIsNumeric IsNumeric {
            get {
                return this.isNumericField;
            }
            set {
                this.isNumericField = value;
            }
        }
        
        /// <remarks/>
        public FreeTextAnswerTypeConstraintsLength Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FreeTextAnswerTypeConstraintsIsNumeric {
        
        private int minValueField;
        
        private bool minValueFieldSpecified;
        
        private int maxValueField;
        
        private bool maxValueFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int minValue {
            get {
                return this.minValueField;
            }
            set {
                this.minValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minValueSpecified {
            get {
                return this.minValueFieldSpecified;
            }
            set {
                this.minValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int maxValue {
            get {
                return this.maxValueField;
            }
            set {
                this.maxValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxValueSpecified {
            get {
                return this.maxValueFieldSpecified;
            }
            set {
                this.maxValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FreeTextAnswerTypeConstraintsLength {
        
        private string minLengthField;
        
        private string maxLengthField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string minLength {
            get {
                return this.minLengthField;
            }
            set {
                this.minLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string maxLength {
            get {
                return this.maxLengthField;
            }
            set {
                this.maxLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/Quest" +
        "ionForm.xsd")]
    public partial class AnswerSpecificationType {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FileUploadAnswer", typeof(FileUploadAnswerType))]
        [System.Xml.Serialization.XmlElementAttribute("FreeTextAnswer", typeof(FreeTextAnswerType))]
        [System.Xml.Serialization.XmlElementAttribute("SelectionAnswer", typeof(SelectionAnswerType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/Quest" +
        "ionForm.xsd")]
    public partial class JavaAppletContentType {
        
        private string appletPathField;
        
        private string appletFilenameField;
        
        private string widthField;
        
        private string heightField;
        
        private ApplicationParameter[] applicationParameterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string AppletPath {
            get {
                return this.appletPathField;
            }
            set {
                this.appletPathField = value;
            }
        }
        
        /// <remarks/>
        public string AppletFilename {
            get {
                return this.appletFilenameField;
            }
            set {
                this.appletFilenameField = value;
            }
        }
        
        /// <remarks/>
        public string Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public string Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ApplicationParameter")]
        public ApplicationParameter[] ApplicationParameter {
            get {
                return this.applicationParameterField;
            }
            set {
                this.applicationParameterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/Quest" +
        "ionForm.xsd", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        Application,
        
        /// <remarks/>
        Binary,
        
        /// <remarks/>
        FormattedContent,
        
        /// <remarks/>
        List,
        
        /// <remarks/>
        Text,
        
        /// <remarks/>
        Title,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class QuestionFormQuestion {
        
        private string questionIdentifierField;
        
        private string displayNameField;
        
        private bool isRequiredField;
        
        private bool isRequiredFieldSpecified;
        
        private ContentType questionContentField;
        
        private AnswerSpecificationType answerSpecificationField;
        
        /// <remarks/>
        public string QuestionIdentifier {
            get {
                return this.questionIdentifierField;
            }
            set {
                this.questionIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public bool IsRequired {
            get {
                return this.isRequiredField;
            }
            set {
                this.isRequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsRequiredSpecified {
            get {
                return this.isRequiredFieldSpecified;
            }
            set {
                this.isRequiredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public ContentType QuestionContent {
            get {
                return this.questionContentField;
            }
            set {
                this.questionContentField = value;
            }
        }
        
        /// <remarks/>
        public AnswerSpecificationType AnswerSpecification {
            get {
                return this.answerSpecificationField;
            }
            set {
                this.answerSpecificationField = value;
            }
        }
    }
}
